config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'devise/registrations'}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Route to capture API post requests and set pre-flight headers
  match "api/participants", to: "application#options", via: :options
  match "api/responses", to: "application#options", via: :options

  resources :participants, only: [:index, :show, :update]

  get "activate/:id", to: "participants#activate", as: :activate
  get "active_index", to: "participants#active_index", as: :active_participants

  #Health Workers
  resources :health_workers, only: [:index, :edit, :new]

  # RAs
  resources :research_assistants, only: [:index, :new, :edit]

  # Supervisors
  resources :supervisors, only: [:index, :new, :edit]

  resources :survey_questions do
    collection { post :import }
  end

  resources :survey_collections
  resources :groups
  resources :surveys
  resources :users, only: [:update]

  # For client-side User and Participant syncing
  namespace "api", constraints: { format: 'json' }  do
    resources :users, only: [:index]
    resources :participants, only: [:create, :index]
    resources :survey_questions, only: [:index]
    resources :groups, only: [:index]
    resources :responses, only: [:create]
  end

  get 'home', to: 'home#index'

  root 'home#index'
end

app/models/participant.rb
class Participant < ActiveRecord::Base
  belongs_to :health_worker, class_name: "User", foreign_key: :health_worker_id
  belongs_to :research_assistant, class_name: "User", foreign_key: :research_assistant_id
  has_many :responses

  validates :patient_identifier, presence: true
  validates :patient_identifier, uniqueness: true
end

app/controllers/api/participants_controller.rb
module Api
  class ParticipantsController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_filter  :verify_authenticity_token
    respond_to :json

    def index
      @participants = Participant.all
      render "participants/index.json"
    end

    def create
      participants = participant_params

      if participants
        Participant.transaction do
          participants.each do |p|

            begin
              ra = User.where(guid: p["research_assistant_id"]).first

              ra_id = ra.try(:id)

              Participant.create({
                guid: p["guid"],
                patient_identifier: p["patient_identifier"],
                first_name: p["first_name"],
                last_name: p["last_name"],
                address: p["address"],
                city: p["city"],
                phone: p["phone"],
                clinic: p["clinic"],
                research_assistant_id: ra_id
            }) unless Participant.where(guid: p["guid"]).any?

            rescue ActiveRecord::RecordNotUnique
              retry
            end
          end
        end
        render json: { success: true, res: "patient data imported" }
      else
        render json: { error: true, res: "No patient data sent" }

      end
    end

    private

    def participant_params
      params.permit(participant: {}, participants: [:patient_identifier, :clinic, :first_name, :last_name, :address, :city, :phone, :guid, :research_assistant_id, :timestamp, :created_at]).require(:participants)
    end
  end
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pending_participants = Participant.where(status: "pending")
    @inactive_participants = Participant.where(status: "ineligible")
  end

  def show
    @participant = Participant.find(params[:id])
  end

  def active_index
    @participants = Participant.where(status: "active")
  end

  def update
    @participant = Participant.where(id: params[:id]).first
    if @participant.update(participant_params)
      after_update_path
    else
      flash[:alert] = @participant.errors.full_messages.join(", ")
      render :index
    end
  end

  def activate
    @participant = Participant.find(params[:id])
    @chws = User.where(role: "Health Worker")
    @assistants = User.where(role: "Research Assistant")
  end

  private

  def participant_params
    params.require(:participant).permit(:status, :patient_identifier, :clinic, :first_name, :last_name, :address, :city, :phone, :guid, :health_worker_id, :research_assistant_id)
  end

  def after_update_path
    redirect_to participants_path, notice: "Successfully updated participant"
  end
end

app/views/participants/activate.html.erb
<div class="row">
  <div class="col-md-12 well text-center">
    <h1>Activate <%= @participant.first_name %> <%= @participant.last_name %></h1>
    <br>
    <%= form_for @participant, html: {role: "form", class: "form-horizontal"} do |f| %>
      <div class="form-group">
        <%= f.label :research_assistant_id, "Research Assistant", class: "col-md-3 control-label" %>
        <div class="col-md-6">
          <%= f.collection_select(:research_assistant_id, @assistants, :id, :last_and_first_name, {}, {class: 'form-control'}) %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :health_worker_id, "Community Health Worker", class: "col-md-3 control-label" %>
        <div class="col-md-6">
          <%= f.collection_select(:health_worker_id, @chws, :id, :last_and_first_name, {}, {class: 'form-control'}) %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-3 col-md-6">
          <%= f.hidden_field :status, value: "active" %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
          <%= link_to "Cancel", participants_path, class: "btn btn-default" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/participants/active_index.html.erb
<%= render partial: 'partials/back', locals: {path: root_path}  %>

<h1>Review Sessions / Assessments</h1>
<table class="table table-bordered table-striped">
  <tr>
    <th>Patient Identifier</th>
    <th>Name</th>
    <th>Interviewer</th>
    <th>Progress (%)</th>
    <th>Next Session</th>
    <th>Issues</th>
  </tr>
  <% @participants.each do |participant| %>
    <tr>
      <td><%= link_to participant.patient_identifier, participant_path(participant.id) %></td>
      <td><%= participant.last_name%>, <%=participant.first_name%></td>
      <td><%= participant.health_worker.last_name%>, <%=participant.health_worker.first_name%></td>
      <td>25%</td>
      <td>Next session datetime</td>
      <td>Issues</td>
    </tr>
  <% end %>
</table>

app/views/participants/index.html.erb
<%= render partial: 'partials/back', locals: {path: root_path} %>

<h1>Review New Registrations</h1>
<ul class="nav nav-tabs" id="participant-table">
  <li class="active">
    <a href="#pending" data-toggle="tab">Pending</a>
  </li>
  <li>
    <a href="#ineligible" data-toggle="tab">Ineligible</a>
  </li>
</ul>
<div class="tab-content">
  <div class="tab-pane active" id="pending">
    <table class="table table-bordered table-striped">
      <tr>
        <th>Patient Identifier</th>
        <th>Name</th>
        <th>Intake date</th>
        <th>clinic</th>
        <th>Activate</th>
        <th>Deactivate</th>
      </tr>
      <% @pending_participants.each do |participant| %>
        <tr>
          <td><%= participant.patient_identifier %></td>
          <td><%= participant.last_name%>, <%=participant.first_name%></td>
          <td><%= participant.created_at.to_s(:long) %> UTC</td>
          <td><%= participant.clinic %></td>
          <td><%= link_to '', activate_path(participant), class: "fa fa-thumbs-up fa-2x", id: "activate_#{participant.id}" %></td>
          <td><%= link_to '', participant_path(id: participant.id, participant: {status: 'ineligible'}), method: :put, class: "fa fa-thumbs-down fa-2x", id: "disqualify_#{participant.id}", :"data-confirm" => "Are you sure you want to deactivate this patient?" %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="tab-pane" id="ineligible">
    <table class="table table-bordered table-striped">
      <tr>
        <th>Patient Identifier</th>
        <th>Name</th>
        <th>Clinic</th>
        <th>Activate</th>
      </tr>
      <% @inactive_participants.each do |participant| %>
        <tr>
          <td><%= participant.patient_identifier %></td>
          <td><%= participant.last_name%>, <%=participant.first_name%></td>
          <td><%= participant.clinic %></td>
          <td><%= link_to '', activate_path(participant), class: "fa fa-thumbs-up fa-2x", id: "activate_#{participant.id}" %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>
<script>

    function tabify() {
        $('#participant-table a').click(function (e) {
            e.preventDefault()
            $(this).tab('show')
        });
    }

    $(document).ready(tabify);
    $(document).on("page:change", tabify);

</script>

app/views/participants/show.html.erb
<%= render partial: 'partials/back', locals: {path: active_participants_path}  %>

<h1>Patient ID: <%= @participant.patient_identifier %></h1>
<div class="row">
  <div class="col-sm-2 col-md-2 col-lg-2">
    <h4 class="text-center session-header">Current Session</h5>
    <div class="current-session">
      <span>5</span>
    </div>
  </div>
  <div class="col-sm-10 col-md-10 col-lg-10">
    <h3>Sessions</h3>
    <table class="table table-bordered table-striped">
      <tr>
        <th>Session #</th>
        <th>Date / Time</th>
        <th>Rescheduled?</th>
        <th>Therapy Type</th>
        <th>Responses</th>
      </tr>
      <!-- Dummy data -->
      <tr>
        <td>1</td>
        <td>8/1/14</td>
        <td>NO</td>
        <td>PST</td>
        <td>Key/Value pair data</td>
      </tr>
    </table>
    <h3>Assessments</h3>
    <table class="table table-bordered table-striped">
      <tr>
        <th>Assessment Name</th>
        <th>Date / Time</th>
        <th>Review</th>
      </tr>
      <!-- Dummy data -->
      <tr>
        <td>First Assessment</td>
        <td>8/1/14</td>
        <td class="text-center"><%=icon('eye fa-2x')%></td>
      </tr>
    </table>
  </div>
</div>