config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'devise/registrations'}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Route to capture API post requests and set pre-flight headers
  match "api/participants", to: "application#options", via: :options
  match "api/responses", to: "application#options", via: :options

  resources :participants, only: [:index, :show, :update]

  get "activate/:id", to: "participants#activate", as: :activate
  get "active_index", to: "participants#active_index", as: :active_participants

  #Health Workers
  resources :health_workers, only: [:index, :edit, :new]

  # RAs
  resources :research_assistants, only: [:index, :new, :edit]

  # Supervisors
  resources :supervisors, only: [:index, :new, :edit]

  resources :survey_questions do
    collection { post :import }
  end

  resources :survey_collections
  resources :groups
  resources :surveys
  resources :users, only: [:update]

  # For client-side User and Participant syncing
  namespace "api", constraints: { format: 'json' }  do
    resources :users, only: [:index]
    resources :participants, only: [:create, :index]
    resources :survey_questions, only: [:index]
    resources :groups, only: [:index]
    resources :responses, only: [:create]
  end

  get 'home', to: 'home#index'

  root 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    before_action :authenticate_user!

    def index
    end
end

app/views/home/index.html.erb
<div class="row">
    <div class="col-sm-12 col-md-12 col-lg-12 navigation">
        <h1>Welcome to Friendship Bench!</h1>
        <div class="well">
            <div class="btn-group btn-group-justified">
              <%= link_to "Manage Supervisors", supervisors_path, class: "btn btn-primary" %>
              <%= link_to "Manage CHWs", health_workers_path, class: "btn btn-success" %>
              <%= link_to "Manage RAs", research_assistants_path, class: "btn btn-warning" %>
            </div>
            <h2 class="text-center">Patient Management</h2>
            <%= link_to "Review New Registrations", participants_path, class: "btn btn-primary" %>
            <%= link_to "Review Sessions / Assessments", active_participants_path, class: "btn btn-success"%>
            <h2 class="text-center">Content</h2>
            <%= link_to "Manage Surveys", survey_questions_path, class: "btn btn-warning" %>
        </div>
    </div>
</div>