config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'devise/registrations'}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Route to capture API post requests and set pre-flight headers
  match "api/participants", to: "application#options", via: :options
  match "api/responses", to: "application#options", via: :options

  resources :participants, only: [:index, :show, :update]

  get "activate/:id", to: "participants#activate", as: :activate
  get "active_index", to: "participants#active_index", as: :active_participants

  #Health Workers
  resources :health_workers, only: [:index, :edit, :new]

  # RAs
  resources :research_assistants, only: [:index, :new, :edit]

  # Supervisors
  resources :supervisors, only: [:index, :new, :edit]

  resources :survey_questions do
    collection { post :import }
  end

  resources :survey_collections
  resources :groups
  resources :surveys
  resources :users, only: [:update]

  # For client-side User and Participant syncing
  namespace "api", constraints: { format: 'json' }  do
    resources :users, only: [:index]
    resources :participants, only: [:create, :index]
    resources :survey_questions, only: [:index]
    resources :groups, only: [:index]
    resources :responses, only: [:create]
  end

  get 'home', to: 'home#index'

  root 'home#index'
end

app/models/survey.rb
class Survey < ActiveRecord::Base
    has_many :survey_questions, dependent: :destroy
    has_many :survey_collections, dependent: :destroy
    has_many :groups, through: :survey_collections
    before_validation :generate_guid,  on: :create

      def generate_guid
        self.guid = SecureRandom.uuid
    end
end

app/controllers/api/surveys_controller.rb
module Api
  class SurveysController < ApplicationController
    skip_before_action :authenticate_user!
    skip_before_filter  :verify_authenticity_token
    respond_to :json

    def index
      @surveys = Survey.all
      render "surveys/index.json"
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!

  before_action :set_survey, only: [:show, :edit, :update, :destroy]
  respond_to :js, :html, :json

  def index
    @surveys = Survey.all
  end

  def show
    respond_with(@survey)
  end

  def new
    @survey = Survey.new
    respond_with(@survey)
  end

  def edit
  end

  def create
    @survey = Survey.new(survey_params)
    @survey.save
    respond_with(@survey)
  end

  def update
    @survey.update(survey_params)
    respond_with(@survey)
  end

  def destroy
    @survey.destroy
    respond_with(@survey)
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])
    end

    def survey_params
      params.require(:survey).permit(:survey_name, survey_ids: [])
    end
end

app/views/surveys/_form.html.erb
<%= form_for(@survey) do |f| %>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey question from being saved:</h2>

      <ul>
      <% @survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :survey_name %><br>
    <%= f.text_field :survey_name, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Edit Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<%= render partial: 'partials/back', locals: {path: root_path}  %>

<h1>Surveys</h1>

<table class="table table-bordered table-striped">
    <tr>
      <th colspan="2"></th>
      <th>Survey Name</th>
    </tr>
    <% @surveys.each do |survey| %>
      <tr>
        <td>
          <%= link_to survey_questions_path(q: {survey_survey_name_cont: survey.survey_name}) do%>
            <%= icon "eye" %>
          <% end %>
        </td>
        <td>
          <%= link_to edit_survey_path(survey) do %>
            <%= icon "edit" %>
          <% end %>
        </td>
        <td><%= survey.survey_name %></td>
      </tr>
    <% end %>
  </table>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @survey.group %>
</p>

<p>
  <strong>Orderer:</strong>
  <%= @survey.orderer %>
</p>

<p>
  <strong>Survey Type:</strong>
  <%= @survey.survey_type %>
</p>

<p>
  <strong>Language:</strong>
  <%= @survey.language %>
</p>

<p>
  <strong>Data label:</strong>
  <%= @survey.data_label %>
</p>

<p>
  <strong>Content:</strong>
  <%= @survey.content %>
</p>

<p>
  <strong>Response0:</strong>
  <%= @survey.response0 %>
</p>

<p>
  <strong>Response0 value:</strong>
  <%= @survey.response0_value %>
</p>

<p>
  <strong>Response1:</strong>
  <%= @survey.response1 %>
</p>

<p>
  <strong>Response1 value:</strong>
  <%= @survey.response1_value %>
</p>

<p>
  <strong>Response2:</strong>
  <%= @survey.response2 %>
</p>

<p>
  <strong>Response2 value:</strong>
  <%= @survey.response2_value %>
</p>

<p>
  <strong>Response3:</strong>
  <%= @survey.response3 %>
</p>

<p>
  <strong>Response3 value:</strong>
  <%= @survey.response3_value %>
</p>

<p>
  <strong>Response4:</strong>
  <%= @survey.response4 %>
</p>

<p>
  <strong>Response4 value:</strong>
  <%= @survey.response4_value %>
</p>

<p>
  <strong>Response5:</strong>
  <%= @survey.response5 %>
</p>

<p>
  <strong>Response5 value:</strong>
  <%= @survey.response5_value %>
</p>

<p>
  <strong>Response6:</strong>
  <%= @survey.response6 %>
</p>

<p>
  <strong>Response6 value:</strong>
  <%= @survey.response6_value %>
</p>

<p>
  <strong>Response7:</strong>
  <%= @survey.response7 %>
</p>

<p>
  <strong>Response7 value:</strong>
  <%= @survey.response7_value %>
</p>

<p>
  <strong>Response8:</strong>
  <%= @survey.response8 %>
</p>

<p>
  <strong>Response8 value:</strong>
  <%= @survey.response8_value %>
</p>

<p>
  <strong>Response9:</strong>
  <%= @survey.response9 %>
</p>

<p>
  <strong>Response9 value:</strong>
  <%= @survey.response9_value %>
</p>

<p>
  <strong>Response10:</strong>
  <%= @survey.response10 %>
</p>

<p>
  <strong>Response10 value:</strong>
  <%= @survey.response10_value %>
</p>

<p>
  <strong>Response11:</strong>
  <%= @survey.response11 %>
</p>

<p>
  <strong>Response11 value:</strong>
  <%= @survey.response11_value %>
</p>

<p>
  <strong>Response12:</strong>
  <%= @survey.response12 %>
</p>

<p>
  <strong>Response12 value:</strong>
  <%= @survey.response12_value %>
</p>

<p>
  <strong>Response13:</strong>
  <%= @survey.response13 %>
</p>

<p>
  <strong>Response13 value:</strong>
  <%= @survey.response13_value %>
</p>

<p>
  <strong>Response14:</strong>
  <%= @survey.response14 %>
</p>

<p>
  <strong>Response14 value:</strong>
  <%= @survey.response14_value %>
</p>

<p>
  <strong>Response15:</strong>
  <%= @survey.response15 %>
</p>

<p>
  <strong>Response15 value:</strong>
  <%= @survey.response15_value %>
</p>

<p>
  <strong>Response16:</strong>
  <%= @survey.response16 %>
</p>

<p>
  <strong>Response16 value:</strong>
  <%= @survey.response16_value %>
</p>

<p>
  <strong>Required:</strong>
  <%= @survey.required %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>