config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {registrations: 'devise/registrations'}

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Route to capture API post requests and set pre-flight headers
  match "api/participants", to: "application#options", via: :options
  match "api/responses", to: "application#options", via: :options

  resources :participants, only: [:index, :show, :update]

  get "activate/:id", to: "participants#activate", as: :activate
  get "active_index", to: "participants#active_index", as: :active_participants

  #Health Workers
  resources :health_workers, only: [:index, :edit, :new]

  # RAs
  resources :research_assistants, only: [:index, :new, :edit]

  # Supervisors
  resources :supervisors, only: [:index, :new, :edit]

  resources :survey_questions do
    collection { post :import }
  end

  resources :survey_collections
  resources :groups
  resources :surveys
  resources :users, only: [:update]

  # For client-side User and Participant syncing
  namespace "api", constraints: { format: 'json' }  do
    resources :users, only: [:index]
    resources :participants, only: [:create, :index]
    resources :survey_questions, only: [:index]
    resources :groups, only: [:index]
    resources :responses, only: [:create]
  end

  get 'home', to: 'home#index'

  root 'home#index'
end

app/controllers/health_workers_controller.rb
class HealthWorkersController < ApplicationController
  before_action :authenticate_user!

  def index
    @health_workers = User.where(role: "Health Worker")
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.where(id: params[:id]).first
  end
end

app/views/health_workers/edit.html.erb
<h1>Edit <%= @user.last_and_first_name %></h1>
<%= render "users/edit", user: @user %>

app/views/health_workers/index.html.erb
<%= render partial: 'partials/back', locals: {path: root_path}  %>

<%= link_to new_health_worker_path, class: "btn btn-warning pull-right" do %>
  <%= icon 'plus' %> Create Health Worker
<% end %>

<h1>Community Health Workers</h1>

<table class="table table-bordered table-striped">
  <tr>
    <th>Name</th>
    <th>PIN</th>
    <th>Email</th>
    <th>Phone</th>
  </tr>
  <% @health_workers.each do |health_worker| %>
    <tr>
      <td><%=link_to "#{health_worker.last_and_first_name}", edit_health_worker_path(health_worker) %></td>
      <td><%= health_worker.pin%></td>
      <td><%= health_worker.email%></td>
      <td><%= health_worker.phone rescue '' %></td>
    </tr>
  <% end %>
</table>

app/views/health_workers/new.html.erb
<h1>Create New Community Health Worker</h1>
<%= form_for @user, url: user_registration_path, method: :post, html: {role: "form", class: "col-sm-12 col-md-12 col-lg-12"} do |f| %>
  <div class="form-group">
    <%= f.label :first_name, class: "control-label" %>
    <%= f.text_field :first_name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :last_name, class: "control-label" %>
    <%= f.text_field :last_name, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "control-label" %>
    <%= f.text_field :email, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :phone, class: "control-label" %>
    <%= f.text_field :phone, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.submit "Submit", class: "btn btn-primary" %>
    <%= link_to "Cancel", health_workers_path, class: "btn btn-default" %>
  </div>
    <%= f.hidden_field :role, value: "Health Worker" %>
<% end %>